### ISSUE TITLE
一键部署问题

### ISSUE THREAD

**Issue by Dinnerbonex3rd** [CA-Lee/kiwawa#13]
请问一下我这里点击一键部署注册账号的时候怎么老是出错啊
![屏幕截图 2023-06-29 161558](https://github.com/CA-Lee/kiwawa/assets/121348180/f8bbea5c-7689-4ed4-881b-f9bed06ed2c9)

**Comment by CA-Lee** [comment]
1. heroku現在沒有免費服務了，不確定你知不知道
2. 這是很久之前設定的一鍵部署，可能是API 有更新所以壞掉了

**Comment by Dinnerbonex3rd** [comment]
> 1. heroku現在沒有免費服務了，不確定你知不知道
> 2. 這是很久之前設定的一鍵部署，可能是API 有更新所以壞掉了

这个样子啊，那个heroku我确实是第一次听说，所以也就不知道关于没有免费服务的事情。关于这个，我能否继续连接discord和line的交互呢？

**Comment by CA-Lee** [comment]
當然可以，不過你（至少）需要一個可以持續執行這個機器人服務的機器，你可以考慮在自己的電腦上搭配ngrok或是使用vercel(一個類似heroku的服務，目前似乎還有免費版)，不過以上你都需要手動架設，沒有一鍵部署了☹️

**Comment by Dinnerbonex3rd** [comment]
好吧，谢谢解答
