### ISSUE TITLE
Deploy 到Heroku和環境變數都設定好之後，卻還是無法收到雙方的Webhook 的meesage event。

### ISSUE THREAD

**Issue by playone** [CA-Lee/kiwawa#5]
Deploy 到Heroku和環境變數都設定好之後，卻還是無法收到雙方的Webhook 的meesage event。

**Comment by playone** [comment]
> Deploy 到Heroku和環境變數都設定好之後，卻還是無法收到雙方的Webhook 的meesage event。

**Comment by CA-Lee** [comment]
要到line官方帳號的設定頁面設定webhook url，url為 `https://(你的heroku網址)/callback`

**Comment by playone** [comment]
是我少加了callback，感謝你的回應
 目前從Line 到Discord 這端有通了。

**想再請問從Discord 到Line 這端是我有少了怎樣的設定嗎? 因為我這邊完全無法看到Discord 發出的log?**

**Comment by playone** [comment]
> 是我少加了callback，感謝你的回應。目前從Line 到Discord 這端有通了。
> 
> **想再請問從Discord 到Line 這端是我有少了怎樣的設定嗎? 因為我這邊完全無法看到Discord 發出的log?**

![image](https://user-images.githubusercontent.com/30642453/152677324-6d8de480-d2ab-4d25-b8f7-1e581d7d05ee.png)

**Comment by CA-Lee** [comment]
d2l是在另一個worker跑，可以檢查一下heroku的頁面是否有顯示啟動兩個服務（一個web一個worker）

**Comment by playone** [comment]
Deploy 完之後，Heroku 預設只有開web service。經由你的提醒之後，打開woker 就可以用了。非常感謝你抽空回應問題~
![image](https://user-images.githubusercontent.com/30642453/152679985-3e353cbc-6d44-49c5-8eb3-718ef0e6edf3.png)
